version: "3.8"

services:
  assetdb:
    build: .
    ports:
      - "4000:4000"
    restart: unless-stopped
    labels:
      - "howl.target=graphql-introspection"
      - "howl.difficulty=hard"
    environment:
      - FLASK_ENV=production
