version: "3.8"

services:
  cloudnotes:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    labels:
      - "howl.target=broken-object-auth"
      - "howl.difficulty=hard"
    environment:
      - FLASK_ENV=production
