version: "3.8"

services:
  dns-zone-transfer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dns-zone-transfer
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:8080"
      - "22:22"
    restart: unless-stopped
    labels:
      - "howl.target=dns-zone-transfer"
      - "howl.difficulty=easy"
